services:
  postgres:
    image: postgres:${PG_VERSION:-16}-bookworm
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_DB: dev
    volumes:
      - ./artifacts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5