name: 'Install cached packages'
runs:
  using: "composite"
  steps:
    - name: Cache apt packages
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: /var/lib/apt/lists
        key: ${{ runner.os }}-apt-1.0

    - name: Install git
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
            curl \
            git \
            jq \
            wget \
            python3-pip

    - name: Cache yq binary
      id: cache-yq
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/yq
        key: ${{ runner.os }}-yq-latest-1.0

    - name: Install yq
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq