name: Build Extensions

on:
  schedule:
    - cron: '0 0 * * *'  # Build giornaliera
  workflow_dispatch:
    inputs:
      extension:
        description: 'Estensione specifica da costruire (lasciare vuoto per tutte)'
        required: false
      pg_version:
        description: 'Versione PostgreSQL'
        required: false
        default: '16'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.extension }}" != "" ]; then
            VERSIONS="${{ github.event.inputs.pg_version }}"
            if [ -z "$VERSIONS" ]; then
              VERSIONS=$(yq e ".extensions.${{ github.event.inputs.extension }}.versions[]" extensions.yml | tr '\n' ' ')
            fi
            matrix=$(jq -n \
              --arg ext "${{ github.event.inputs.extension }}" \
              --arg vers "$VERSIONS" \
              '{include: [{"extension": $ext, "pg_version": ($vers | split(" ")[0])}]}')
          else
            matrix=$(yq e -o=json \
              '.extensions | to_entries | {include: map(.value.versions[] as $v | {"extension": .key, "pg_version": $v})}' \
              extensions.yml)
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            jq \
            wget

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Extension
        run: |
          chmod +x ./scripts/build-extension.sh
          ./scripts/build-extension.sh ${{ matrix.extension }} ${{ matrix.pg_version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.extension }}-pg${{ matrix.pg_version }}
          path: artifacts/*.tar.gz
          retention-days: 5

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ matrix.extension }}-pg${{ matrix.pg_version }}-${{ github.sha }}
          files: artifacts/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}